### ISSUE TITLE
Hexo搭建博客系列：（六）Hexo添加Disqus评论 | DeppWang's Blog

### ISSUE THREAD

**Issue by DeppWang** [DeppWang/deppwang.github.io#31]
https://depp.wang/2017/06/15/Hexo6/ 

 国内的评论系统畅言需要ICP备案，网易云跟帖没用过，那天鼓捣鼓捣。博主博客使用的是国外的Disqus评论系统,只能科学上网后使用。 Disqus配置使用Disqus网址：https://disqus.com/ 打开链接后， 可以直接用Facebook，Twitter以及 Google 登录；也可以用邮箱注册后登录。 配置 Disqus登录后，点击首页的GET STARTED 按钮，点击图示按钮。

**Comment by VincentTam** [comment]
Hi, this is the maintainer of @staticmanlab, a public GitLab instance of [Staicman](https://staticman.net/).  Here's some shortcomings of the commenting systems mentioned above.

1. Disqus is difficult to access for non programmers in the PRC, as reported in https://github.com/Huxpro/huxpro.github.io/issues/258#issuecomment-430842480.
1. Gitment, Gitalk and Utterance support only GitHub, and they require user login before commenting. This can scare away many non programmers from leaving a comment to your posts. Besides, comments are part of the site's static content, not a software package problem. As a result, using GtiHub issues for comment storage is wrong in principle and bad in terms of SEO.
2. Commento is not free as in free beer.  For a personal blog with small traffic, you might find a monthly fee of $5 too expensive.
3. Disqus and Isso contain a 3rd-party script to be loaded during page rendering. The code block for loading each of them shows that the static comments are not rendered as static HTML code. This hinders search engines from grabbing the comments, which are part of the site's content.  As a result, that leads to suboptimal SEO.

You may avoid these problems by switching to Staticman, which makes use of GitHub/GitLab Pull/Merge Requests instead of issues. Under Staticman's model, static comments are YML/JSON files stored in the remote GitHub/GitLab repo (usually under data/comments, configurable through the path parameter in root-level staticman.yml), and through a static blog generator (Jekyll/Hugo/etc), the stored data are rendered as part of the content. This gives a total ownership of a static site's comments.

**Comment by DeppWang** [comment]
> @VincentTam
> Hi, this is the maintainer of @staticmanlab, a public GitLab instance of [Staicman](https://staticman.net/).  Here's some shortcomings of the commenting systems mentioned above.
> 
> 1. Disqus is difficult to access for non programmers in the PRC, as reported in https://github.com/Huxpro/huxpro.github.io/issues/258#issuecomment-430842480.
> 1. Gitment, Gitalk and Utterance support only GitHub, and they require user login before commenting. This can scare away many non programmers from leaving a comment to your posts. Besides, comments are part of the site's static content, not a software package problem. As a result, using GtiHub issues for comment storage is wrong in principle and bad in terms of SEO.
> 2. Commento is not free as in free beer.  For a personal blog with small traffic, you might find a monthly fee of $5 too expensive.
> 3. Disqus and Isso contain a 3rd-party script to be loaded during page rendering. The code block for loading each of them shows that the static comments are not rendered as static HTML code. This hinders search engines from grabbing the comments, which are part of the site's content.  As a result, that leads to suboptimal SEO.
> 
> You may avoid these problems by switching to Staticman, which makes use of GitHub/GitLab Pull/Merge Requests instead of issues. Under Staticman's model, static comments are YML/JSON files stored in the remote GitHub/GitLab repo (usually under data/comments, configurable through the path parameter in root-level staticman.yml), and through a static blog generator (Jekyll/Hugo/etc), the stored data are rendered as part of the content. This gives a total ownership of a static site's comments.

Thank you tell me, but I think Gitalk more suitable for me.

**Comment by VincentTam** [comment]
> Thank you tell me, but I think Gitalk more suitable for me.

In which way ?  I'd love to hear.
